### PR TITLE
Introduces .editorconfig and .rustfmt.toml

### PR DESCRIPTION
**Pull request by LiquidityC**
This aims to maintain the current "dominant" formatting in the project
and alos help contributors conform to the setup.

### CODE REVIEW

**Comment by LiquidityC** [comment]
'cargo fmt' has been run in this commit too. Seems it's only my additions which actually got major modifications. :laughing:

**Comment by envis10n** [comment]
Just need to redo this to ensure a clean merge after the other PR

**Comment by envis10n** [comment]
I'll be pushing directly into master with this same PR.

**Comment by LiquidityC** [comment]
OH, ok. just fixed it though :smile:

**Pull request closed without merging**
